/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.monocalculator;

/**
 *
 * @author LoneDespair
 */
public class Classic extends javax.swing.JFrame {
    double previousNum;
    double currentNum;
    char operation;
    
    public void addNum(int num) {
        
    }
    

    /**
     * Creates new form Classic
     */
    public Classic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        num_1 = new javax.swing.JButton();
        primaryDisplay = new javax.swing.JLabel();
        num_2 = new javax.swing.JButton();
        num_3 = new javax.swing.JButton();
        num_4 = new javax.swing.JButton();
        num_5 = new javax.swing.JButton();
        num_6 = new javax.swing.JButton();
        num_7 = new javax.swing.JButton();
        num_8 = new javax.swing.JButton();
        num_9 = new javax.swing.JButton();
        num_10 = new javax.swing.JButton();
        num_11 = new javax.swing.JButton();
        num_12 = new javax.swing.JButton();
        num_13 = new javax.swing.JButton();
        num_14 = new javax.swing.JButton();
        num_15 = new javax.swing.JButton();
        num_16 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        num_1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num_1.setText("1");
        num_1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_1ActionPerformed(evt);
            }
        });

        primaryDisplay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        primaryDisplay.setText("jLabel1");
        primaryDisplay.setFocusable(false);
        primaryDisplay.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        num_2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num_2.setText("1");
        num_2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_2ActionPerformed(evt);
            }
        });

        num_3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num_3.setText("1");
        num_3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_3ActionPerformed(evt);
            }
        });

        num_4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num_4.setText("1");
        num_4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_4ActionPerformed(evt);
            }
        });

        num_5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num_5.setText("1");
        num_5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_5ActionPerformed(evt);
            }
        });

        num_6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num_6.setText("1");
        num_6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_6ActionPerformed(evt);
            }
        });

        num_7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num_7.setText("1");
        num_7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_7ActionPerformed(evt);
            }
        });

        num_8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num_8.setText("1");
        num_8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_8ActionPerformed(evt);
            }
        });

        num_9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num_9.setText("1");
        num_9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_9ActionPerformed(evt);
            }
        });

        num_10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num_10.setText("1");
        num_10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_10ActionPerformed(evt);
            }
        });

        num_11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num_11.setText("1");
        num_11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_11ActionPerformed(evt);
            }
        });

        num_12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num_12.setText("1");
        num_12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_12ActionPerformed(evt);
            }
        });

        num_13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num_13.setText("1");
        num_13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_13ActionPerformed(evt);
            }
        });

        num_14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num_14.setText("1");
        num_14.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_14ActionPerformed(evt);
            }
        });

        num_15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num_15.setText("1");
        num_15.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num_15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_15ActionPerformed(evt);
            }
        });

        num_16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        num_16.setText("1");
        num_16.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        num_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(primaryDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(num_1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num_3, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num_2, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num_4, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(num_5, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num_6, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num_7, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num_8, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(num_12, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num_11, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num_10, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num_9, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(num_15, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num_16, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num_14, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num_13, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(primaryDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num_1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num_3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num_2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num_4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num_5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num_6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num_7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num_8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num_12, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num_11, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num_10, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num_9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num_15, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num_16, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num_14, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(num_13, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_1ActionPerformed
        System.out.println("Clicked num 1");
    }//GEN-LAST:event_num_1ActionPerformed

    private void num_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_2ActionPerformed

    private void num_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_3ActionPerformed

    private void num_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_4ActionPerformed

    private void num_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_5ActionPerformed

    private void num_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_6ActionPerformed

    private void num_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_7ActionPerformed

    private void num_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_8ActionPerformed

    private void num_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_9ActionPerformed

    private void num_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_10ActionPerformed

    private void num_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_11ActionPerformed

    private void num_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_12ActionPerformed

    private void num_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_13ActionPerformed

    private void num_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_14ActionPerformed

    private void num_15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_15ActionPerformed

    private void num_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Classic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Classic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Classic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Classic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Classic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton num_1;
    private javax.swing.JButton num_10;
    private javax.swing.JButton num_11;
    private javax.swing.JButton num_12;
    private javax.swing.JButton num_13;
    private javax.swing.JButton num_14;
    private javax.swing.JButton num_15;
    private javax.swing.JButton num_16;
    private javax.swing.JButton num_2;
    private javax.swing.JButton num_3;
    private javax.swing.JButton num_4;
    private javax.swing.JButton num_5;
    private javax.swing.JButton num_6;
    private javax.swing.JButton num_7;
    private javax.swing.JButton num_8;
    private javax.swing.JButton num_9;
    private javax.swing.JLabel primaryDisplay;
    // End of variables declaration//GEN-END:variables
}
